spring.config.import=file:.env[.properties]

spring.application.name=API

#Conexão com o BD da API
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.url=${DB_URL}
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop